spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
        dialect: org.hibernate.dialect.MySQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            scope:
              - profile
              - email
            authorization-grant-type: authorization_code
            client-name: Google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

jwt:
  secret-key: ${JWT_SECRET_KEY}
  expire-length: 86400000 # 1 day (24 hours in milliseconds)

api-key:
  date-checker: ${DATE_CHECKER_API_KEY}

url:
  access-token: https://oauth2.googleapis.com/token
  profile: https://www.googleapis.com/oauth2/v3/userinfo

springdoc:
  api-docs:
    path: /v3/api-docs # API 문서 경로
  swagger-ui:
    path: /swagger-ui/index.html # Swagger UI 경로 수정